" Example Vim graphical configuration.
" Copy to ~/.gvimrc or ~/_gvimrc.

set guifont=Menlo\ Regular:h18     " Font family and font size.
set antialias                   " MacVim: smooth fonts.
set encoding=utf-8              " Use UTF-8 everywhere.
set guioptions-=T               " Hide toolbar.
"set background=light            " Background.
set lines=100 columns=200       " Window dimensions.
set cmdheight=3                 " Rows for commands at bottom
set fuopt+=maxhorz

set guioptions-=r               " Don't show right scrollbar


